name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable=114.0.5735.90-1

    - name: Download ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=114.0.5735.90
        wget -N https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv -f chromedriver /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver
        rm chromedriver_linux64.zip

    - name: Install dependencies
      run: dotnet restore SwagLabsPOM/SwagLabsPOM.csproj

    - name: Build
      run: dotnet build SwagLabsPOM/SwagLabsPOM.csproj --no-restore

    - name: Run tests
      run: dotnet test SwagLabsPOM/SwagLabsPOM.csproj --verbosity normal
